import { getExperienceCards } from '@/lib/experiences'
import CategoryClient, { type CategoryExp } from './CategoryClient'

// Static fallback for experiences not yet in the database
const STATIC_EXPERIENCES: CategoryExp[] = [
  { slug: 'pottery-making-class',   title: 'Pottery Making Class',             area: 'Ubud',       price: 450000, rating: 4.9, reviews: 128, duration: '2.5 hours',  maxGuests: 8,  image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80',    badge: 'Bestseller', category: 'art-craft',  subcategory: 'Pottery'           },
  { slug: 'silver-jewelry-workshop', title: 'Silver Jewelry Workshop',          area: 'Canggu',     price: 580000, rating: 4.8, reviews: 94,  duration: '3 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'art-craft',  subcategory: 'Jewelry'           },
  { slug: 'batik-painting-workshop', title: 'Batik Painting Workshop',          area: 'Ubud',       price: 380000, rating: 4.7, reviews: 64,  duration: '3 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'art-craft',  subcategory: 'Painting'          },
  { slug: 'wood-carving-workshop',   title: 'Wood Carving Workshop',            area: 'Mas, Ubud',  price: 500000, rating: 4.6, reviews: 47,  duration: '4 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'art-craft',  subcategory: 'Wood Carving'      },
  { slug: 'natural-dye-workshop',    title: 'Natural Dye Workshop',             area: 'Sidemen',    price: 380000, rating: 4.7, reviews: 31,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'art-craft',  subcategory: 'Textile'           },
  { slug: 'rattan-weaving-class',    title: 'Rattan Weaving Class',             area: 'Sidemen',    price: 350000, rating: 4.8, reviews: 29,  duration: '2.5 hours',  maxGuests: 8,  image: 'https://images.unsplash.com/photo-1605522469906-3fe226b356bc?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'art-craft',  subcategory: 'Weaving'           },
  { slug: 'sound-healing-session',   title: 'Sound Healing Journey',            area: 'Ubud',       price: 350000, rating: 4.9, reviews: 212, duration: '90 min',     maxGuests: 12, image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&auto=format&fit=crop&q=80',    badge: 'Top Rated',  category: 'wellness-healing',   subcategory: 'Sound Healing'     },
  { slug: 'jamu-wellness-ritual',    title: 'Traditional Jamu Ritual',          area: 'Ubud',       price: 480000, rating: 4.8, reviews: 73,  duration: '2 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'wellness-healing',   subcategory: 'Spa & Ritual'      },
  { slug: 'sunrise-yoga-ubud',       title: 'Sunrise Yoga in the Rice Fields',  area: 'Ubud',       price: 280000, rating: 4.9, reviews: 156, duration: '75 min',     maxGuests: 10, image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',    badge: 'Bestseller', category: 'wellness-healing',   subcategory: 'Yoga'              },
  { slug: 'meditation-temple',       title: 'Guided Meditation at Tirta Empul', area: 'Gianyar',    price: 320000, rating: 4.7, reviews: 88,  duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'wellness-healing',   subcategory: 'Meditation'        },
  { slug: 'water-temple-ceremony',   title: 'Water Temple Purification',        area: 'Gianyar',    price: 420000, rating: 4.7, reviews: 84,  duration: '3 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1604999333679-b86d54738315?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culture',    subcategory: 'Temple & Ceremony' },
  { slug: 'traditional-dance-class', title: 'Legong Dance Masterclass',         area: 'Ubud',       price: 390000, rating: 4.8, reviews: 61,  duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culture',    subcategory: 'Dance & Music'     },
  { slug: 'kecak-fire-dance',        title: 'Kecak Fire Dance at Uluwatu',      area: 'Uluwatu',    price: 250000, rating: 4.9, reviews: 318, duration: '1.5 hours',  maxGuests: 20, image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&auto=format&fit=crop&q=80',    badge: 'Iconic',     category: 'culture',    subcategory: 'Dance & Music'     },
  { slug: 'balinese-history-tour',   title: 'Old Bali Heritage Walk',           area: 'Klungkung',  price: 350000, rating: 4.7, reviews: 42,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culture',    subcategory: 'History Tour'      },
  { slug: 'balinese-cooking-class',  title: 'Balinese Cooking Class',           area: 'Ubud',       price: 420000, rating: 4.9, reviews: 187, duration: '4 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80',    badge: 'Bestseller', category: 'culinary',   subcategory: 'Cooking Class'     },
  { slug: 'coffee-plantation-tour',  title: 'Coffee Plantation & Tasting Tour', area: 'Kintamani',  price: 320000, rating: 4.8, reviews: 143, duration: '3 hours',    maxGuests: 12, image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80',   badge: null,         category: 'culinary',   subcategory: 'Coffee & Tea'      },
  { slug: 'ubud-market-food-tour',   title: 'Ubud Market Food Tour',            area: 'Ubud',       price: 280000, rating: 4.8, reviews: 97,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culinary',   subcategory: 'Market Tour'       },
  { slug: 'mount-batur-sunrise',     title: 'Mount Batur Sunrise Trek',         area: 'Kintamani',  price: 650000, rating: 4.8, reviews: 241, duration: '6 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&auto=format&fit=crop&q=80',    badge: 'Top Rated',  category: 'nature-outdoors',     subcategory: 'Sunrise'           },
  { slug: 'rice-terrace-trek',       title: 'Tegallalang Rice Terrace Trek',    area: 'Ubud',       price: 320000, rating: 4.7, reviews: 103, duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1573790387438-4da905039392?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'nature-outdoors',     subcategory: 'Rice Terrace'      },
  { slug: 'waterfall-hidden-canyon', title: 'Hidden Waterfall Canyon Hike',     area: 'Aling-Aling',price: 450000, rating: 4.9, reviews: 89,  duration: '5 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1552083375-1447ce886485?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'nature-outdoors',     subcategory: 'Waterfall'         },
  { slug: 'surfing-lesson-canggu',   title: 'Surfing Lesson for Beginners',     area: 'Canggu',     price: 400000, rating: 4.8, reviews: 176, duration: '2 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80',    badge: 'Bestseller', category: 'water-activities', subcategory: 'Surfing'           },
  { slug: 'snorkeling-amed',         title: 'Snorkelling at USAT Liberty Wreck',area: 'Amed',       price: 550000, rating: 4.9, reviews: 138, duration: '4 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=600&auto=format&fit=crop&q=80',    badge: 'Top Rated',  category: 'water-activities', subcategory: 'Snorkelling'       },
  { slug: 'sup-seminyak',            title: 'Stand-Up Paddleboard at Seminyak', area: 'Seminyak',   price: 350000, rating: 4.6, reviews: 52,  duration: '1.5 hours',  maxGuests: 6,  image: 'https://images.unsplash.com/photo-1530870110042-98b2cb110834?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'water-activities', subcategory: 'Stand-Up Paddle'   },
  // Culinary
  { slug: 'balinese-spice-workshop', title: 'Balinese Spice & Herb Workshop',   area: 'Ubud',       price: 360000, rating: 4.9, reviews: 84,  duration: '2.5 hours',  maxGuests: 8,  image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',    badge: 'Top Rated',  category: 'culinary',   subcategory: 'Spice & Herb'      },
  { slug: 'jamu-making-class',       title: 'Traditional Jamu Making Class',    area: 'Ubud',       price: 320000, rating: 4.8, reviews: 61,  duration: '2 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culinary',   subcategory: 'Spice & Herb'      },
  { slug: 'tempeh-fermentation',     title: 'Tempeh Fermentation Workshop',     area: 'Sidemen',    price: 390000, rating: 4.7, reviews: 38,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culinary',   subcategory: 'Fermentation'      },
  { slug: 'balinese-dessert-class',  title: 'Balinese Dessert & Jajan Pasar',   area: 'Ubud',       price: 300000, rating: 4.8, reviews: 47,  duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',    badge: null,         category: 'culinary',   subcategory: 'Dessert & Sweets'  },
  { slug: 'farm-table-ubud',         title: 'Farm to Table Lunch in the Jungle',area: 'Ubud',       price: 520000, rating: 4.9, reviews: 73,  duration: '4 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&auto=format&fit=crop&q=80',    badge: 'Bestseller', category: 'culinary',   subcategory: 'Farm to Table'     },
  // Local Experts
  { slug: 'vacation-photoshoot-uluwatu', title: 'Golden Hour Vacation Photoshoot',  area: 'Uluwatu',   price: 850000, rating: 4.9, reviews: 116, duration: '90 min',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'local-experts', subcategory: 'Photographers'          },
  { slug: 'private-island-guide',        title: 'Private Guide — Your Bali, Your Pace', area: 'Ubud',  price: 700000, rating: 4.8, reviews: 89,  duration: 'Full day',  maxGuests: 6,  image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'local-experts', subcategory: 'Guides'                 },
  { slug: 'private-yoga-practitioner',   title: 'Private Yoga & Breathwork Session', area: 'Canggu',   price: 550000, rating: 4.9, reviews: 74,  duration: '75 min',    maxGuests: 4,  image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Wellness Practitioners' },
  { slug: 'trusted-babysitter-seminyak', title: 'Trusted Babysitter & Kids Activities', area: 'Seminyak', price: 350000, rating: 4.9, reviews: 67, duration: 'Per 4 hours', maxGuests: 3, image: 'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=600&auto=format&fit=crop&q=80', badge: null,        category: 'local-experts', subcategory: 'Childcare'              },
  { slug: 'dog-walker-pet-sitter',       title: 'Dog Walking & Pet Sitting',        area: 'Canggu',    price: 250000, rating: 4.8, reviews: 53,  duration: 'Per visit', maxGuests: 2,  image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Pet Care'               },
  { slug: 'creative-mentor-session',     title: 'One-on-One Creative Mentor Session', area: 'Ubud',    price: 480000, rating: 4.8, reviews: 41,  duration: '2 hours',   maxGuests: 2,  image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Creative Mentors'       },
  { slug: 'private-driver-day-rate',     title: 'Private Driver — Full Day Charter', area: 'Seminyak', price: 650000, rating: 4.9, reviews: 138, duration: 'Up to 10 hours', maxGuests: 5, image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'local-experts', subcategory: 'Drivers'             },
  // Rentals — Transportation
  { slug: 'scooter-rental-canggu',       title: 'Scooter Rental — Canggu',          area: 'Canggu',   price: 80000,  rating: 4.8, reviews: 312, duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'rentals', subcategory: 'Scooter'         },
  { slug: 'motorbike-rental-ubud',       title: 'Motorbike Rental — Ubud',          area: 'Ubud',     price: 120000, rating: 4.7, reviews: 184, duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Motorbike'       },
  { slug: 'bicycle-rental-seminyak',     title: 'City Bicycle Rental',              area: 'Seminyak', price: 50000,  rating: 4.9, reviews: 97,  duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', category: 'rentals', subcategory: 'Bicycle'         },
  { slug: 'ebike-rental-ubud',           title: 'E-Bike Rental — Explore Ubud',    area: 'Ubud',     price: 150000, rating: 4.8, reviews: 61,  duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'E-Bike'          },
  // Rentals — Lifestyle
  { slug: 'villa-rental-canggu',         title: 'Private Pool Villa — Canggu',      area: 'Canggu',   price: 1800000,rating: 4.9, reviews: 78,  duration: 'Per night', maxGuests: 6, image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', category: 'rentals', subcategory: 'Villa'           },
  { slug: 'coworking-space-canggu',      title: 'Coworking Day Pass — Canggu',      area: 'Canggu',   price: 120000, rating: 4.8, reviews: 143, duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Workspace'       },
  { slug: 'photography-studio-ubud',     title: 'Private Photography Studio',       area: 'Ubud',     price: 350000, rating: 4.7, reviews: 34,  duration: 'Per 4 hrs', maxGuests: 4, image: 'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Studio'          },
  // Rentals — Adventure
  { slug: 'surfboard-rental-canggu',     title: 'Surfboard Rental — Canggu Beach',  area: 'Canggu',   price: 70000,  rating: 4.8, reviews: 229, duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'rentals', subcategory: 'Surfboard'       },
  { slug: 'camping-gear-kit',            title: 'Full Camping Gear Kit',            area: 'Kintamani',price: 200000, rating: 4.7, reviews: 42,  duration: 'Per night', maxGuests: 4, image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Camping Gear'    },
  { slug: 'diving-equipment-amed',       title: 'Full Dive Equipment Rental',       area: 'Amed',     price: 250000, rating: 4.9, reviews: 88,  duration: 'Per day',   maxGuests: 1, image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated', category: 'rentals', subcategory: 'Diving Equipment' },

  // ── Art & Craft (extra) ──────────────────────────────────────────────────────
  { slug: 'ceramic-bowl-workshop',       title: 'Ceramic Bowl & Glaze Workshop',    area: 'Ubud',       price: 420000, rating: 4.8, reviews: 76,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1490312278390-ab64016e0aa9?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'art-craft',  subcategory: 'Pottery'          },
  { slug: 'gold-leaf-painting-class',    title: 'Traditional Gold Leaf Painting',   area: 'Ubud',       price: 450000, rating: 4.9, reviews: 55,  duration: '3 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'art-craft',  subcategory: 'Painting'         },
  { slug: 'ikat-weaving-sidemen',        title: 'Traditional Ikat Weaving — Sidemen', area: 'Sidemen',  price: 400000, rating: 4.7, reviews: 33,  duration: '3.5 hours',  maxGuests: 6,  image: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'art-craft',  subcategory: 'Weaving'          },
  { slug: 'lontar-leaf-engraving',       title: 'Lontar Leaf Manuscript Engraving', area: 'Klungkung',  price: 480000, rating: 4.8, reviews: 28,  duration: '2.5 hours',  maxGuests: 6,  image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'art-craft',  subcategory: 'Wood Carving'     },
  { slug: 'gold-silver-ring-making',     title: 'Gold & Silver Ring Making Class',  area: 'Canggu',     price: 620000, rating: 4.8, reviews: 61,  duration: '3 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'art-craft',  subcategory: 'Jewelry'          },
  { slug: 'endek-textile-workshop',      title: 'Balinese Endek Textile Workshop',  area: 'Gianyar',    price: 360000, rating: 4.7, reviews: 44,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'art-craft',  subcategory: 'Textile'          },

  // ── Wellness & Healing (extra) ───────────────────────────────────────────────
  { slug: 'breathwork-pranayama',        title: 'Breathwork & Pranayama Session',   area: 'Ubud',       price: 300000, rating: 4.9, reviews: 118, duration: '75 min',     maxGuests: 8,  image: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'wellness-healing',   subcategory: 'Breathwork'       },
  { slug: 'holotropic-breathwork',       title: 'Holotropic Breathwork Journey',    area: 'Canggu',     price: 450000, rating: 4.8, reviews: 49,  duration: '2 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'wellness-healing',   subcategory: 'Breathwork'       },
  { slug: 'balinese-massage-ritual',     title: 'Traditional Balinese Massage',     area: 'Seminyak',   price: 380000, rating: 4.8, reviews: 204, duration: '90 min',     maxGuests: 2,  image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'wellness-healing',   subcategory: 'Spa & Ritual'     },
  { slug: 'yin-yoga-nidra',              title: 'Yin Yoga & Yoga Nidra',            area: 'Canggu',     price: 250000, rating: 4.9, reviews: 143, duration: '90 min',     maxGuests: 12, image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'wellness-healing',   subcategory: 'Yoga'             },
  { slug: 'tibetan-singing-bowl',        title: 'Private Tibetan Singing Bowl Session', area: 'Ubud',   price: 400000, rating: 4.9, reviews: 87,  duration: '75 min',     maxGuests: 4,  image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'wellness-healing',   subcategory: 'Sound Healing'    },
  { slug: 'metta-meditation-retreat',    title: 'Metta Loving-Kindness Meditation', area: 'Ubud',       price: 280000, rating: 4.8, reviews: 97,  duration: '90 min',     maxGuests: 10, image: 'https://images.unsplash.com/photo-1602192509154-0b900ee1f851?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'wellness-healing',   subcategory: 'Meditation'       },
  { slug: 'boreh-body-treatment',        title: 'Boreh Traditional Body Treatment', area: 'Ubud',       price: 450000, rating: 4.8, reviews: 58,  duration: '2 hours',    maxGuests: 2,  image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'wellness-healing',   subcategory: 'Spa & Ritual'     },

  // ── Culture (extra) ──────────────────────────────────────────────────────────
  { slug: 'bahasa-bali-introduction',    title: 'Balinese Language Introduction',   area: 'Ubud',       price: 220000, rating: 4.7, reviews: 36,  duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culture',    subcategory: 'Language'         },
  { slug: 'gamelan-music-workshop',      title: 'Gamelan Music Workshop',           area: 'Ubud',       price: 350000, rating: 4.8, reviews: 72,  duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culture',    subcategory: 'Dance & Music'    },
  { slug: 'wayang-shadow-puppet',        title: 'Wayang Shadow Puppet Workshop',    area: 'Ubud',       price: 320000, rating: 4.7, reviews: 44,  duration: '2.5 hours',  maxGuests: 8,  image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culture',    subcategory: 'History Tour'     },
  { slug: 'pura-besakih-temple-tour',    title: 'Besakih Mother Temple Guided Tour',area: 'Karangasem', price: 380000, rating: 4.8, reviews: 119, duration: '4 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1604999333679-b86d54738315?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culture',    subcategory: 'Temple & Ceremony'},
  { slug: 'barong-mask-dance',           title: 'Barong & Keris Dance Performance', area: 'Batubulan',  price: 150000, rating: 4.8, reviews: 263, duration: '1 hour',     maxGuests: 30, image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&auto=format&fit=crop&q=80', badge: 'Iconic',     category: 'culture',    subcategory: 'Dance & Music'    },
  { slug: 'east-bali-villages-tour',     title: 'Ancient East Bali Villages Tour',  area: 'Karangasem', price: 420000, rating: 4.7, reviews: 58,  duration: '6 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culture',    subcategory: 'History Tour'     },

  // ── Nature & Outdoors (extra) ────────────────────────────────────────────────
  { slug: 'campuhan-ridge-walk',         title: 'Campuhan Ridge Sunrise Walk',      area: 'Ubud',       price: 180000, rating: 4.8, reviews: 167, duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1573790387438-4da905039392?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'nature-outdoors',     subcategory: 'Trekking'         },
  { slug: 'jungle-trekking-sidemen',     title: 'Sidemen Valley Jungle Trek',       area: 'Sidemen',    price: 380000, rating: 4.8, reviews: 74,  duration: '4 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'nature-outdoors',     subcategory: 'Trekking'         },
  { slug: 'sekumpul-waterfall-trek',     title: 'Sekumpul Waterfall Hidden Trek',   area: 'Singaraja',  price: 480000, rating: 4.9, reviews: 96,  duration: '5 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1552083375-1447ce886485?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'nature-outdoors',     subcategory: 'Waterfall'        },
  { slug: 'bali-bird-walk',              title: 'Bali Bird Watching Walk — Ubud',   area: 'Ubud',       price: 350000, rating: 4.7, reviews: 51,  duration: '3 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'nature-outdoors',     subcategory: 'Wildlife'         },
  { slug: 'bali-safari-wildlife',        title: 'Bali Safari & Marine Park',        area: 'Gianyar',    price: 550000, rating: 4.7, reviews: 88,  duration: '4 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1534759926685-3c6e4b9b5a6e?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'nature-outdoors',     subcategory: 'Wildlife'         },
  { slug: 'mount-agung-sunrise-trek',    title: 'Mount Agung Sunrise Summit Trek',  area: 'Karangasem', price: 950000, rating: 4.9, reviews: 62,  duration: '8 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1499962707695-0786c0e41de0?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'nature-outdoors',     subcategory: 'Sunrise'          },
  { slug: 'jatiluwih-rice-terrace-walk', title: 'Jatiluwih UNESCO Rice Terrace Walk',area: 'Tabanan',   price: 280000, rating: 4.8, reviews: 133, duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1580674684031-7c6b7f6b7f6b?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'nature-outdoors',     subcategory: 'Rice Terrace'     },

  // ── Water Activities (extra) ─────────────────────────────────────────────────
  { slug: 'freediving-course-amed',      title: 'Freediving Course — Amed',         area: 'Amed',       price: 1200000,rating: 4.9, reviews: 67,  duration: 'Full day',   maxGuests: 4,  image: 'https://images.unsplash.com/photo-1559825481-12a05cc00344?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'water-activities', subcategory: 'Freediving'       },
  { slug: 'scuba-intro-dive-amed',       title: 'Discover Scuba Diving — Amed',     area: 'Amed',       price: 850000, rating: 4.9, reviews: 114, duration: '3 hours',    maxGuests: 4,  image: 'https://images.unsplash.com/photo-1682687220742-aba19b51a6c0?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'water-activities', subcategory: 'Scuba Diving'     },
  { slug: 'surf-lesson-kuta',            title: 'Surf Lesson — Kuta Beach',         area: 'Kuta',       price: 350000, rating: 4.7, reviews: 289, duration: '2 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'water-activities', subcategory: 'Surfing'          },
  { slug: 'nusa-penida-snorkel-trip',    title: 'Nusa Penida Snorkel Day Trip',     area: 'Nusa Penida',price: 650000, rating: 4.9, reviews: 342, duration: 'Full day',   maxGuests: 10, image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=600&auto=format&fit=crop&q=80', badge: 'Bestseller', category: 'water-activities', subcategory: 'Snorkelling'    },
  { slug: 'white-water-rafting-ayung',   title: 'White Water Rafting — Ayung River',area: 'Ubud',       price: 450000, rating: 4.8, reviews: 198, duration: '2.5 hours',  maxGuests: 8,  image: 'https://images.unsplash.com/photo-1530866495561-507c9faab2ed?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'water-activities', subcategory: 'Stand-Up Paddle' },
  { slug: 'sup-lake-batur',              title: 'SUP on Lake Batur — Volcano Views',area: 'Kintamani',  price: 380000, rating: 4.8, reviews: 57,  duration: '2 hours',    maxGuests: 6,  image: 'https://images.unsplash.com/photo-1530870110042-98b2cb110834?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'water-activities', subcategory: 'Stand-Up Paddle' },
  { slug: 'scuba-manta-ray-nusa',        title: 'Manta Ray Scuba Dive — Nusa Penida',area: 'Nusa Penida',price: 1100000,rating: 5.0, reviews: 78,  duration: 'Full day',   maxGuests: 4,  image: 'https://images.unsplash.com/photo-1682687220742-aba19b51a6c0?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'water-activities', subcategory: 'Scuba Diving'     },

  // ── Culinary (extra) ─────────────────────────────────────────────────────────
  { slug: 'sate-lilit-masterclass',      title: 'Sate Lilit & Lawar Masterclass',   area: 'Ubud',       price: 380000, rating: 4.8, reviews: 79,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culinary',   subcategory: 'Cooking Class'    },
  { slug: 'kintamani-coffee-experience', title: 'Kintamani Coffee Bean Experience',  area: 'Kintamani',  price: 280000, rating: 4.7, reviews: 112, duration: '2 hours',    maxGuests: 10, image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culinary',   subcategory: 'Coffee & Tea'     },
  { slug: 'seminyak-food-tour',          title: 'Seminyak Street Food Night Tour',   area: 'Seminyak',   price: 350000, rating: 4.8, reviews: 88,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culinary',   subcategory: 'Market Tour'      },
  { slug: 'organic-jungle-lunch',        title: 'Organic Farm-to-Fork Jungle Lunch',area: 'Ubud',       price: 480000, rating: 4.9, reviews: 64,  duration: '3 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culinary',   subcategory: 'Farm to Table'    },
  { slug: 'kombucha-kefir-workshop',     title: 'Kombucha & Kefir Fermentation Lab', area: 'Canggu',    price: 320000, rating: 4.7, reviews: 42,  duration: '2.5 hours',  maxGuests: 8,  image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culinary',   subcategory: 'Fermentation'     },
  { slug: 'klepon-dessert-class',        title: 'Klepon & Laklak Dessert Class',     area: 'Gianyar',    price: 260000, rating: 4.8, reviews: 53,  duration: '2 hours',    maxGuests: 8,  image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'culinary',   subcategory: 'Dessert & Sweets' },

  // ── Local Experts (extra) ────────────────────────────────────────────────────
  { slug: 'drone-photography-uluwatu',   title: 'Drone & Aerial Photography Session',area: 'Uluwatu',   price: 1200000,rating: 4.9, reviews: 47,  duration: '2 hours',    maxGuests: 4,  image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Photographers'         },
  { slug: 'family-guide-kids-bali',      title: 'Family Guide — Kid-Friendly Bali', area: 'Ubud',       price: 750000, rating: 4.9, reviews: 61,  duration: 'Full day',   maxGuests: 8,  image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Guides'                },
  { slug: 'reiki-energy-healer',         title: 'Reiki & Energy Healing Session',   area: 'Canggu',     price: 480000, rating: 4.8, reviews: 58,  duration: '75 min',     maxGuests: 2,  image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Wellness Practitioners'},
  { slug: 'airport-private-driver',      title: 'Airport Transfer & Island Driver', area: 'Seminyak',   price: 350000, rating: 4.9, reviews: 213, duration: 'Per trip',   maxGuests: 5,  image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'local-experts', subcategory: 'Drivers'               },

  // ── Rentals (extra) ──────────────────────────────────────────────────────────
  { slug: 'motorbike-rental-seminyak',   title: 'Honda CRF Motorbike Rental',       area: 'Seminyak',   price: 150000, rating: 4.7, reviews: 97,  duration: 'Per day',    maxGuests: 1,  image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Motorbike'            },
  { slug: 'longboard-rental-canggu',     title: 'Longboard & Mini-Mal Rental',      area: 'Canggu',     price: 90000,  rating: 4.8, reviews: 143, duration: 'Per day',    maxGuests: 1,  image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Surfboard'            },
  { slug: 'villa-rental-ubud',           title: 'Jungle Pool Villa — Ubud',         area: 'Ubud',       price: 2200000,rating: 4.9, reviews: 53,  duration: 'Per night',  maxGuests: 6,  image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&auto=format&fit=crop&q=80', badge: 'Top Rated',  category: 'rentals', subcategory: 'Villa'                },
  { slug: 'kids-bicycle-rental',         title: 'Kids Bicycle & Family Set Rental', area: 'Canggu',     price: 40000,  rating: 4.8, reviews: 68,  duration: 'Per day',    maxGuests: 1,  image: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80', badge: null,         category: 'rentals', subcategory: 'Bicycle'              },
]

export const dynamic = 'force-dynamic'

const WATER_ACTIVITY_SLUGS = new Set(['water-activities'])

export default async function CategoryPage({ params }: { params: { category: string } }) {
  const { category } = params
  const isWater = category === 'water-activities'

  const dbCards = await getExperienceCards()
  const dbSlugs = new Set(dbCards.map(c => c.slug))

  const dbExps: CategoryExp[] = dbCards
    .filter(c => isWater ? WATER_ACTIVITY_SLUGS.has(c.categorySlug) : c.categorySlug === category)
    .map(c => ({
      slug: c.slug,
      title: c.title,
      area: c.area,
      price: c.price,
      rating: c.rating,
      reviews: c.reviews,
      duration: c.duration,
      maxGuests: c.maxGuests,
      image: c.photo,
      badge: c.badge,
      category: isWater ? 'water-activities' : c.categorySlug,
      subcategory: null,
    }))

  const staticOnly = STATIC_EXPERIENCES.filter(e => {
    if (isWater) return WATER_ACTIVITY_SLUGS.has(e.category) && !dbSlugs.has(e.slug)
    return e.category === category && !dbSlugs.has(e.slug)
  }).map(e => isWater ? { ...e, category: 'water-activities' } : e)

  const initialExperiences = [...dbExps, ...staticOnly]

  return <CategoryClient categorySlug={category} initialExperiences={initialExperiences} />
}
