name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_LO4ABKWQXLHJG6f7TzI3GihT
          VERCEL_PROJECT_ID: prj_ztuhc1o0GTePjdYvZziNVgQ8xgEE
